/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu Mar 14 14:37:50 2019. */

#include "monitor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Node_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, Node, nodeId, nodeId, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Node, address, nodeId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, Node, channel, address, 0),
    PB_LAST_FIELD
};

const pb_field_t DCtrlReq_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, DCtrlReq, node, node, &Node_fields),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, DCtrlReq, cmd, node, 0),
    PB_LAST_FIELD
};

const pb_field_t SensorValue_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, SensorValue, node, node, &Node_fields),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, SensorValue, value1, node, 0),
    PB_LAST_FIELD
};

const pb_field_t NCtrlRsp_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, NCtrlRsp, node, node, &Node_fields),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, NCtrlRsp, errorcode, node, 0),
    PB_LAST_FIELD
};

const pb_field_t NodeSend_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, NodeSend, sid, sid, 0),
    PB_ONEOF_FIELD(payload,   2, MESSAGE , ONEOF, STATIC  , OTHER, NodeSend, sensorValue, sid, &SensorValue_fields),
    PB_ONEOF_FIELD(payload,   3, MESSAGE , ONEOF, STATIC  , UNION, NodeSend, control, sid, &NCtrlRsp_fields),
    PB_LAST_FIELD
};

const pb_field_t DeviceSend_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, DeviceSend, sid, sid, 0),
    PB_ONEOF_FIELD(payload,   2, MESSAGE , ONEOF, STATIC  , OTHER, DeviceSend, control, sid, &DCtrlReq_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DCtrlReq, node) < 65536 && pb_membersize(SensorValue, node) < 65536 && pb_membersize(NCtrlRsp, node) < 65536 && pb_membersize(NodeSend, payload.sensorValue) < 65536 && pb_membersize(NodeSend, payload.control) < 65536 && pb_membersize(DeviceSend, payload.control) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Node_DCtrlReq_SensorValue_NCtrlRsp_NodeSend_DeviceSend)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DCtrlReq, node) < 256 && pb_membersize(SensorValue, node) < 256 && pb_membersize(NCtrlRsp, node) < 256 && pb_membersize(NodeSend, payload.sensorValue) < 256 && pb_membersize(NodeSend, payload.control) < 256 && pb_membersize(DeviceSend, payload.control) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Node_DCtrlReq_SensorValue_NCtrlRsp_NodeSend_DeviceSend)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
